from __future__ import annotations

from dataclasses import dataclass


@dataclass
class DataOp:
    """An explicit one-time ClickHouse data operation.

    Data-ops are authored by the user, applied once, and never re-emitted by the
    differ.  They are the schema-vs-data boundary made concrete: the differ owns
    schema, the user owns data operations, and the two surfaces never cross.

    Attributes:
        name: Unique name for this data-op (used for dedup across migrations).
        forward: The SQL to execute forward.
        rollback: SQL to undo, or ``None`` for irreversible ops.
        requires_confirmation: If True, prompt before applying destructive ops.
    """
    name: str
    forward: str
    rollback: str | None = None
    requires_confirmation: bool = False


def data_op(
    *,
    name: str,
    forward: str,
    rollback: str | None = None,
    requires_confirmation: bool = False,
) -> DataOp:
    """Declare a one-time data operation for ClickHouse.

    Data-ops are never generated by diffing model vs snapshot; they are
    authored explicitly, reviewed like a migration, and applied once.  They
    occupy the same migration stream as schema changes but are recorded
    separately so they NEVER re-emit on subsequent runs.

    Args:
        name: Unique name for dedup across migrations.
        forward: The SQL to execute forward.
        rollback: SQL to undo, or ``None`` for irreversible (a warning is
            shown at apply time).
        requires_confirmation: Prompt before apply for destructive ops
            (partition drops, mutations, etc.).

    Example::

        from dbwarden.databases.clickhouse import data_op

        drop_old = data_op(
            name="drop_2023_01",
            forward="ALTER TABLE events DROP PARTITION '202301'",
            rollback=None,
            requires_confirmation=True,
        )
    """
    return DataOp(
        name=name,
        forward=forward,
        rollback=rollback,
        requires_confirmation=requires_confirmation,
    )
